### ISSUE TITLE
[Feature request]Plan to support VS2022?

### ISSUE THREAD

**Issue by sh0ou** [madskristensen/TrailingWhitespace#61]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: none

### Description
Hello.
Is there any plan to support VS2022 for this extension?
I would like to use this wonderful extension in VS2022 as well.

**Comment by lbioux** [comment]
Yes please!

**Comment by madskristensen** [comment]
It's right here: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TrailingWhitespace64

**Comment by jamesmanningrapidscale** [comment]
@madskristensen is there any chance the page for the 32-bit version at https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TrailingWhitespaceVisualizer could please give a pointer to the 64-bit one for VS 2022 users? 🙏  Up until finding this issue, I thought there was no 2022 version since the 32-bit version just didn't list or mention 2022 at all.
