### ISSUE TITLE
Feature: Delayed visualize

### ISSUE THREAD

**Issue by paiden** [madskristensen/TrailingWhitespace#9]
Would be nice if the whitespace visualization would have a little (maybe configurable) delay, so that when someone enters some valid - but temporary - trailing whitespace (e.g. after a operator), the editor wouldn't show up the trailing whitespace immediately to reduce 'flickering' while typing.

**Comment by drewnoakes** [comment]
Yes this would make the addin less annoying. I've only just installed it myself but am considering uninstalling due to this.

Looks like an easy PR. Anyone have any pointers to where to start on this?

I think it'd just be easiest if the highlighting of trailing whitespace did not occur on the current line.

**Comment by orand** [comment]
See the TrailingSpaces plugin for Sublime Text for inspiration on configuration options and implementation details. They have an Include Current Line option, as well as only modified lines, and more. 
https://github.com/SublimeText/TrailingSpaces/blob/master/README.md
